In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

import pprint
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn import metrics

from sklearn.svm import SVR

%matplotlib inline

In [2]:
# importing the dataset we prepared and saved using Data Cleaning Notebook
rice = pd.read_csv("/Users/macbook/Documents/BTP/Notebook/BTP/Satellite/Rice_Ready.csv")
rice = rice.drop(["Unnamed: 0"],axis=1)
rice.head()

State_Name ind_district  Crop_Year  Season  Crop  Area  Production  Value  \
0  Chandigarh   chandigarh       2005  kharif  Rice    50         250   5.00   
1  Chandigarh   chandigarh       2007  kharif  Rice    50         250   5.00   
2  Chandigarh   chandigarh       2008  kharif  Rice    20         100   5.00   
3  Chandigarh   chandigarh       2009  kharif  Rice    20         100   5.00   
4  Chandigarh   chandigarh       2010  kharif  Rice    20         103   5.15   

    X1   X2    ...      11_B10_Mn  12_B1_Mn  12_B2_Mn  12_B3_Mn  12_B4_Mn  \
0  400  500    ...           10.0       5.0       5.0       5.0       5.0   
1  250  250    ...           10.0      10.0      10.0      10.0      10.0   
2  250  250    ...           10.0      10.0      10.0      10.0      10.0   
3  100  250    ...            5.0       5.0       5.0       5.0       5.0   
4  100  100    ...           10.0       5.0       5.0       5.0       5.0   

   12_B5_Mn  12_B6_Mn  12_B7_Mn  12_B9_Mn  12_B10_Mn  
0       5.0       5.0       5.0       5.0        5.0  
1      10.0      10.0      10.0      10.0       10.0  
2      10.0      10.0      10.0      10.0       10.0  
3       5.0       5.0       5.0       5.0        5.0  
4       5.0       5.0       5.0       5.0        5.0  

[5 rows x 334 columns]

In [3]:
colss = list(rice.columns.values)

In [4]:
len(colss)

334

### 334 = 10 + 216 + 108

In [5]:
select = colss[8:226]

In [6]:
X = rice[select]
y = rice["Value"]*1000

In [7]:
X.describe()

X1            X2      1_B1_M      1_B1_V      1_B2_M  \
count  3.280000e+02  3.280000e+02  328.000000  328.000000  328.000000   
mean   1.950245e+05  1.919716e+05    9.182927   13.259146    6.496951   
std    2.925836e+05  2.925789e+05   25.121663   39.173220   20.421551   
min    2.000000e+00  6.000000e+00    0.000000    0.000000    0.000000   
25%    1.400000e+04  1.528500e+04    0.000000    0.000000    0.000000   
50%    8.149350e+04  7.543400e+04    0.000000    0.000000    0.000000   
75%    2.586915e+05  2.510000e+05    0.000000    5.000000    0.000000   
max    1.710000e+06  1.710000e+06  208.000000  297.000000  181.000000   

           1_B2_V      1_B3_M      1_B3_V      1_B4_M      1_B4_V  \
count  328.000000  328.000000  328.000000  328.000000  328.000000   
mean    10.216463    7.277439   12.277439   10.829268   13.719512   
std     32.127405   22.737147   39.657315   26.708211   35.481149   
min      0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000   
75%      3.000000    0.000000    3.000000    2.000000    8.000000   
max    258.000000  201.000000  324.000000  215.000000  242.000000   

          ...          12_B5_M     12_B5_V     12_B6_M     12_B6_V  \
count     ...       328.000000  328.000000  328.000000  328.000000   
mean      ...         4.385467    4.972324   12.556707    9.899831   
std       ...        12.157602   19.456249   25.190668   21.751825   
min       ...         0.000000    0.000000    0.000000    0.000000   
25%       ...         0.000000    0.000000    0.000000    0.000000   
50%       ...         0.000000    0.000000    0.000000    0.000000   
75%       ...         0.000000    2.000000    9.000000   11.250000   
max       ...        70.000000  291.000000  125.000000  240.000000   

          12_B7_M     12_B7_V     12_B9_M     12_B9_V    12_B10_M     12_B10_V  
count  328.000000  328.000000  328.000000  328.000000  328.000000   328.000000  
mean     2.426999    3.474390   14.232249   11.854234  221.661484   342.035772  
std      8.235961   16.688323   27.993943   25.203706  180.640592   598.626471  
min      0.000000    0.000000    0.000000    0.000000    1.000000     0.000000  
25%      0.000000    0.000000    0.000000    0.000000   51.500000    22.000000  
50%      0.000000    0.000000    0.000000    0.000000  222.500000   157.500000  
75%      0.000000    0.000000   10.750000   17.000000  329.750000   429.750000  
max     55.000000  270.000000  141.000000  270.000000  771.000000  8040.000000  

[8 rows x 218 columns]

In [8]:
# Z-Score Normalization 

colms = list(X.columns)
for col in colms:
    col_zscore = col + '_zscore'
    X[col_zscore] = (X[col] - X[col].mean())/X[col].std(ddof=0)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [9]:
cols = list(X.columns.values)
len(cols)

436

In [32]:
# Contains all the features (Last 2 years Crop Production and the Satellite Data)
select = cols[218:436]
X_all = X[select]

# Just the last 2 years Crop Production
select1 = cols[218:220]
X_crp = X[select1]

# Just the Satellite Data
select2 = cols[220:436]
X_sat = X[select2]

# ---------------------------------------------------------------------
# With all the features together
# ---------------------------------------------------------------------

### Avg RMSE for Linear Regression

In [11]:
clf = LinearRegression()
scores = cross_val_score(clf, X_all, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\nAvg RMSE is "+str(scores.mean()))

[ 391955.98677226   30716.17271021   32015.23840967   51595.08478481
   55681.15855367]

Avg RMSE is 112392.728246


/Users/macbook/Library/Python/2.7/lib/python/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


## Support Vector Regression (SVR)

### RBF Kernel

In [12]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=8000.0, epsilon=0.1, kernel='rbf', gamma=0.001)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1001.56936493   934.53462579   927.19294425   510.36585607   792.53322231]
('\n\nAvg RMSE is ', 833.23920267072026)


In [13]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=2000.0, epsilon=0.1, kernel='rbf', gamma=0.008)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  899.97544879   877.1688262   1007.47422578   578.86809173   767.31332759]
('\n\nAvg RMSE is ', 826.15998401704314)


In [14]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=1000000.0, epsilon=0.1, kernel='rbf', gamma=0.000001)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  786.16034517   885.43348522  1213.19019481   516.87862934   792.5500076 ]
('\n\nAvg RMSE is ', 838.84253242753005)


# ---------------------------------------------------------------------
# With only Last 2 Years Crop Production
# ---------------------------------------------------------------------

### Linear Regression

In [15]:
clf = LinearRegression()
scores = cross_val_score(clf, X_crp, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1065.63585702   857.23595343   822.13094399   554.39487643   704.46495431]
('\n\nAvg RMSE is ', 800.77251703573052)


## SVR

In [16]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=500000.0, epsilon=0.1, kernel='rbf', gamma=0.0008)
scores = cross_val_score(clf, X_crp, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1122.52109861   782.51768706   818.44643068   558.35682966   597.68271737]
('\n\nAvg RMSE is ', 775.9049526763938)


In [17]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=8000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
scores = cross_val_score(clf, X_crp, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1124.94452355   789.3795181    635.23208725   568.28402579   603.87158373]
('\n\nAvg RMSE is ', 744.34234768539648)


# ---------------------------------------------------------------------
# With only Satellite Data
# ---------------------------------------------------------------------

### Avg RMSE for Linear Regression

In [18]:
clf = LinearRegression()
scores = cross_val_score(clf, X_sat, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1096649.30846409    57754.97135963    39092.52014173   111666.57491367
    69970.82187998]
('\n\nAvg RMSE is ', 275026.83935182099)


# Support Vector Regression (SVR)

### RBF Kernel

In [19]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=1000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
scores = cross_val_score(clf, X_sat, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  869.97972186   909.00034756  1356.3789098    669.4493212    748.80356142]
('\n\nAvg RMSE is ', 910.72237236657566)


# -----------------------------------------------------
# Dimension Reduction

In [20]:
from sklearn.decomposition import PCA

In [33]:
def fPCA(x): 
    pca = PCA(n_components=x)
    pcax = pca.fit_transform(X_all)

    # 5 Fold CV, to calculate avg RMSE
    clf = SVR(C=2000.0, epsilon=0.1, kernel='rbf', gamma=0.008)
    scores = cross_val_score(clf, pcax, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
    for i in range(0,5):
        scores[i] = sqrt(-1*scores[i])

    print(scores)
    avg_rmse = scores.mean()
    print("\n\nAvg RMSE is ",scores.mean())

In [34]:
fPCA(42)

[ 892.97364473  885.57712686  988.60029939  574.95550189  771.30844956]
('\n\nAvg RMSE is ', 822.68300448471223)


# ------------------------------------------------------
# XGBoost

In [35]:
import xgboost as xgb

In [36]:

# prepare dict of params for xgboost to run with
xgb_params = {
    'n_trees': 500, 
    'eta': 0.005,
    'max_depth': 4,
    'subsample': 0.95,
    'objective': 'reg:linear',
    'eval_metric': 'rmse',
    'base_score': np.mean(y), # base prediction = mean(target)
    'silent': 1
}

In [37]:
# form DMatrices for Xgboost training
dtrain = xgb.DMatrix(X_all, y)
# dtest = xgb.DMatrix(test)

# xgboost, cross-validation
cv_result = xgb.cv(xgb_params, 
                   dtrain, 
                   num_boost_round=500, # increase to have better results (~700)
                   early_stopping_rounds=50,
                   verbose_eval=50, 
                   show_stdv=False
                  )

num_boost_rounds = len(cv_result)
print(num_boost_rounds)

[0]	train-rmse:966.262	test-rmse:966.419
[50]	train-rmse:816.615	test-rmse:855.193
[100]	train-rmse:703.539	test-rmse:777.552
[150]	train-rmse:616.777	test-rmse:725.507
[200]	train-rmse:547.886	test-rmse:689.038
[250]	train-rmse:492.388	test-rmse:661.626
[300]	train-rmse:446.941	test-rmse:641.844
[350]	train-rmse:409.583	test-rmse:627.207
[400]	train-rmse:376.658	test-rmse:615.539
[450]	train-rmse:347.248	test-rmse:605.922
[499]	train-rmse:321.225	test-rmse:598.574
500


In [38]:
# train model
model = xgb.train(dict(xgb_params, silent=0), dtrain, num_boost_round=num_boost_rounds)

In [39]:
# check f2-score (to get higher score - increase num_boost_round in previous cell)
from sklearn.metrics import r2_score

# now fixed, correct calculation
print(r2_score(dtrain.get_label(), model.predict(dtrain)))

0.86400705514


In [47]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y, test_size=0.2, random_state=1)

dtest = xgb.DMatrix(X_test)

y_predict = model.predict(dtest)
rmse = sqrt(mean_squared_error(y_predict, y_test))
print(rmse)

383.723078633


In [48]:
yt = y_test.as_matrix()
print(type(yt))

<type 'numpy.ndarray'>


In [49]:
p = pd.DataFrame()
p["y_predicted"] = y_predict
p["y_test"] = yt

p["y_predicted"] = p["y_predicted"].round(decimals=1)
# p["y_test"] = p["y_test"].round(decimals=1)
p.describe()

y_predicted       y_test
count    66.000000    66.000000
mean   2650.137695  2651.320556
std     814.986877  1087.275670
min    1583.900024  1077.262693
25%    2045.550018  1750.887515
50%    2448.250000  2318.003603
75%    3124.999939  3576.059357
max    4518.100098  5150.000000

In [51]:
# print (p)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X_crp, y, test_size=0.2, random_state=1)

clf = SVR(C=8000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
clf.fit(X_train, y_train)
y_predict = clf.predict(X_test)
rmse = sqrt(mean_squared_error(y_predict, y_test))
print(rmse)



777.939254138


In [56]:
yt = y_test.as_matrix()
p = pd.DataFrame()
p["y_predicted"] = y_predict
p["y_test"] = yt

p["y_predicted"] = p["y_predicted"].round(decimals=1)
# p["y_test"] = p["y_test"].round(decimals=1)
p.describe()

y_predicted       y_test
count    66.000000    66.000000
mean   2587.830303  2651.320556
std     736.545480  1087.275670
min    2020.000000  1077.262693
25%    2079.250000  1750.887515
50%    2346.800000  2318.003603
75%    2740.325000  3576.059357
max    4624.700000  5150.000000

In [57]:
print (p)

    y_predicted       y_test
0        2517.8  2558.195412
1        2190.0  2747.000895
2        2818.4  2341.998346
3        2324.3  1732.000963
4        2052.1  2480.046948
5        4547.0  4697.416974
6        2020.0  1461.538462
7        2078.5  1574.705565
8        2512.1  2611.992716
9        2096.8  2074.378719
10       2020.2  5150.000000
11       3172.2  4114.942529
12       2074.0  1420.727435
13       3178.1  3907.407407
14       2686.5  3085.127174
15       2101.3  1567.065346
16       2613.5  3587.126762
17       2756.4  3446.135971
18       2021.1  1514.450867
19       2173.6  2282.976951
20       2467.5  2257.006161
21       4351.6  4254.166667
22       2394.6  2263.001328
23       2041.9  3676.626641
24       2232.3  3070.175439
25       2081.5  1229.885893
26       2074.2  1995.848635
27       2692.1  3631.417885
28       2382.9  2227.004889
29       2020.7  1555.555556
..          ...          ...
36       2882.1  1658.000797
37       2020.2  1514.563107
38       4624.

In [44]:
# # y_pred = model.predict(dtest)

# # 5 Fold CV, to calculate avg RMSE
# # clf = SVR(C=1000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
# scores = cross_val_score(model, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
# for i in range(0,5):
#     scores[i] = sqrt(-1*scores[i])
    
# print(scores)
# avg_rmse = scores.mean()
# print("\n\nAvg RMSE is ",scores.mean())