In [23]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

import pprint
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import cross_val_score
from sklearn import metrics

from sklearn.svm import SVR

%matplotlib inline

In [41]:
# importing the dataset we prepared and saved using Data Cleaning Notebook
rice = pd.read_csv("/Users/macbook/Documents/BTP/Notebook/BTP/Satellite/Rice_Ready.csv")
rice = rice.drop(["Unnamed: 0"],axis=1)
rice.head()

State_Name ind_district  Crop_Year  Season  Crop  Area  Production  Value  \
0  Chandigarh   chandigarh       2005  kharif  Rice    50         250   5.00   
1  Chandigarh   chandigarh       2007  kharif  Rice    50         250   5.00   
2  Chandigarh   chandigarh       2008  kharif  Rice    20         100   5.00   
3  Chandigarh   chandigarh       2009  kharif  Rice    20         100   5.00   
4  Chandigarh   chandigarh       2010  kharif  Rice    20         103   5.15   

    X1   X2    ...      11_B10_Mn  12_B1_Mn  12_B2_Mn  12_B3_Mn  12_B4_Mn  \
0  400  500    ...           10.0       5.0       5.0       5.0       5.0   
1  250  250    ...           10.0      10.0      10.0      10.0      10.0   
2  250  250    ...           10.0      10.0      10.0      10.0      10.0   
3  100  250    ...            5.0       5.0       5.0       5.0       5.0   
4  100  100    ...           10.0       5.0       5.0       5.0       5.0   

   12_B5_Mn  12_B6_Mn  12_B7_Mn  12_B9_Mn  12_B10_Mn  
0       5.0       5.0       5.0       5.0        5.0  
1      10.0      10.0      10.0      10.0       10.0  
2      10.0      10.0      10.0      10.0       10.0  
3       5.0       5.0       5.0       5.0        5.0  
4       5.0       5.0       5.0       5.0        5.0  

[5 rows x 334 columns]

In [42]:
colss = list(rice.columns.values)

In [43]:
len(colss)

334

### 334 = 10 + 216 + 108

In [44]:
select = colss[8:226]

In [45]:
X = rice[select]
y = rice["Value"]*1000

In [46]:
X.describe()

X1            X2      1_B1_M      1_B1_V      1_B2_M  \
count  3.280000e+02  3.280000e+02  328.000000  328.000000  328.000000   
mean   1.950245e+05  1.919716e+05    9.182927   13.259146    6.496951   
std    2.925836e+05  2.925789e+05   25.121663   39.173220   20.421551   
min    2.000000e+00  6.000000e+00    0.000000    0.000000    0.000000   
25%    1.400000e+04  1.528500e+04    0.000000    0.000000    0.000000   
50%    8.149350e+04  7.543400e+04    0.000000    0.000000    0.000000   
75%    2.586915e+05  2.510000e+05    0.000000    5.000000    0.000000   
max    1.710000e+06  1.710000e+06  208.000000  297.000000  181.000000   

           1_B2_V      1_B3_M      1_B3_V      1_B4_M      1_B4_V  \
count  328.000000  328.000000  328.000000  328.000000  328.000000   
mean    10.216463    7.277439   12.277439   10.829268   13.719512   
std     32.127405   22.737147   39.657315   26.708211   35.481149   
min      0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000   
75%      3.000000    0.000000    3.000000    2.000000    8.000000   
max    258.000000  201.000000  324.000000  215.000000  242.000000   

          ...          12_B5_M     12_B5_V     12_B6_M     12_B6_V  \
count     ...       328.000000  328.000000  328.000000  328.000000   
mean      ...         4.385467    4.972324   12.556707    9.899831   
std       ...        12.157602   19.456249   25.190668   21.751825   
min       ...         0.000000    0.000000    0.000000    0.000000   
25%       ...         0.000000    0.000000    0.000000    0.000000   
50%       ...         0.000000    0.000000    0.000000    0.000000   
75%       ...         0.000000    2.000000    9.000000   11.250000   
max       ...        70.000000  291.000000  125.000000  240.000000   

          12_B7_M     12_B7_V     12_B9_M     12_B9_V    12_B10_M     12_B10_V  
count  328.000000  328.000000  328.000000  328.000000  328.000000   328.000000  
mean     2.426999    3.474390   14.232249   11.854234  221.661484   342.035772  
std      8.235961   16.688323   27.993943   25.203706  180.640592   598.626471  
min      0.000000    0.000000    0.000000    0.000000    1.000000     0.000000  
25%      0.000000    0.000000    0.000000    0.000000   51.500000    22.000000  
50%      0.000000    0.000000    0.000000    0.000000  222.500000   157.500000  
75%      0.000000    0.000000   10.750000   17.000000  329.750000   429.750000  
max     55.000000  270.000000  141.000000  270.000000  771.000000  8040.000000  

[8 rows x 218 columns]

In [47]:
# Z-Score Normalization 

colms = list(X.columns)
for col in colms:
    col_zscore = col + '_zscore'
    X[col_zscore] = (X[col] - X[col].mean())/X[col].std(ddof=0)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [48]:
cols = list(X.columns.values)
len(cols)

436

In [54]:
# Contains all the features (Last 2 years Crop Production and the Satellite Data)
select = cols[218:436]
X_all = X[select]

# Just the last 2 years Crop Production
select1 = cols[218:220]
X_crp = X[select1]

# Just the Satellite Data
select2 = cols[220:436]
X_sat = X[select2]

# ---------------------------------------------------------------------
# With all the features together
# ---------------------------------------------------------------------

### Avg RMSE for Linear Regression

In [55]:
clf = LinearRegression()
scores = cross_val_score(clf, X_all, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 391955.98677226   30716.17271021   32015.23840967   51595.08478481
   55681.15855367]
('\n\nAvg RMSE is ', 112392.72824612369)


## Support Vector Regression (SVR)

### RBF Kernel

In [61]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=500000.0, epsilon=0.1, kernel='rbf', gamma=0.0008)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1660.86596576  1328.39986173  1037.23975696   747.35666676   764.10175116]
('\n\nAvg RMSE is ', 1107.5928004727516)


In [76]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=8000.0, epsilon=0.1, kernel='rbf', gamma=0.001)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1001.56936493   934.53462579   927.19294425   510.36585607   792.53322231]
('\n\nAvg RMSE is ', 833.23920267072026)


In [93]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=2000.0, epsilon=0.1, kernel='rbf', gamma=0.008)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  899.97544879   877.1688262   1007.47422578   578.86809173   767.31332759]
('\n\nAvg RMSE is ', 826.15998401704314)


In [99]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=1000000.0, epsilon=0.1, kernel='rbf', gamma=0.000001)
scores = cross_val_score(clf, X_all, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  786.16034517   885.43348522  1213.19019481   516.87862934   792.5500076 ]
('\n\nAvg RMSE is ', 838.84253242753005)


# ---------------------------------------------------------------------
# With only Last 2 Years Crop Production
# ---------------------------------------------------------------------

### Linear Regression

In [57]:
clf = LinearRegression()
scores = cross_val_score(clf, X_crp, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1065.63585702   857.23595343   822.13094399   554.39487643   704.46495431]
('\n\nAvg RMSE is ', 800.77251703573052)


## SVR

In [101]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=500000.0, epsilon=0.1, kernel='rbf', gamma=0.0008)
scores = cross_val_score(clf, X_crp, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1122.52109861   782.51768706   818.44643068   558.35682966   597.68271737]
('\n\nAvg RMSE is ', 775.9049526763938)


In [113]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=8000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
scores = cross_val_score(clf, X_crp, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1124.94452355   789.3795181    635.23208725   568.28402579   603.87158373]
('\n\nAvg RMSE is ', 744.34234768539648)


# ---------------------------------------------------------------------
# With only Satellite Data
# ---------------------------------------------------------------------

### Avg RMSE for Linear Regression

In [59]:
clf = LinearRegression()
scores = cross_val_score(clf, X_sat, y, cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])
    
print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[ 1096649.30846409    57754.97135963    39092.52014173   111666.57491367
    69970.82187998]
('\n\nAvg RMSE is ', 275026.83935182099)


# Support Vector Regression (SVR)

### RBF Kernel

In [120]:
# 5 Fold CV, to calculate avg RMSE
clf = SVR(C=1000.0, epsilon=0.1, kernel='rbf', gamma=0.01)
scores = cross_val_score(clf, X_sat, y.values.ravel(), cv=5, scoring='neg_mean_squared_error')
for i in range(0,5):
    scores[i] = sqrt(-1*scores[i])

print(scores)
avg_rmse = scores.mean()
print("\n\nAvg RMSE is ",scores.mean())

[  869.97972186   909.00034756  1356.3789098    669.4493212    748.80356142]
('\n\nAvg RMSE is ', 910.72237236657566)
